/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentcar.layerd.view;
import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rentcar.layerd.controller.CategoryController;
import rentcar.layerd.dto.CarReturnDto;

import rentcar.layerd.dto.CategoryDto;
import java.time.LocalDateTime;  
import java.time.format.DateTimeFormatter;  
import static javax.print.attribute.Size2DSyntax.MM;
import rentcar.layerd.controller.CarReturnController;
import rentcar.layerd.controller.RentDetailsController;


/**
 *
 * @author TOSHIBA
 */
public class CarReturnView extends javax.swing.JFrame {
    
    private CarReturnController carReturnController;
    private RentDetailsController rentDetailsController;

    /**
     * Creates new form CategoryView
     */
    public CarReturnView() {
       carReturnController=new CarReturnController ();
       rentDetailsController=new RentDetailsController();
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        caridetxt = new javax.swing.JTextField();
        idlabel1 = new javax.swing.JLabel();
        rentidtext = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        savebtn1 = new javax.swing.JButton();
        namelabel1 = new javax.swing.JLabel();
        custidetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 153, 102));

        headerlabel.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("CarHire");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(1145, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namelabel.setText("Car ID");
        jPanel1.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        caridetxt.setBackground(new java.awt.Color(255, 204, 102));
        caridetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        caridetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        caridetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridetxtActionPerformed(evt);
            }
        });
        jPanel1.add(caridetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 350, 40));

        idlabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idlabel1.setText("Rent ID");
        jPanel1.add(idlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        rentidtext.setBackground(new java.awt.Color(255, 204, 102));
        rentidtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rentidtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        rentidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentidtextActionPerformed(evt);
            }
        });
        jPanel1.add(rentidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 350, 40));

        btnback.setBackground(new java.awt.Color(255, 153, 0));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("D:\\Projects\\LayerdArchitecture\\rentcar-layerd\\src\\images\\iconback.png")); // NOI18N
        btnback.setText("Back");
        btnback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 180, 50));

        savebtn1.setBackground(new java.awt.Color(255, 153, 0));
        savebtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savebtn1.setIcon(new javax.swing.ImageIcon("D:\\Projects\\LayerdArchitecture\\rentcar-layerd\\src\\images\\iconsave.png")); // NOI18N
        savebtn1.setText("  Save");
        savebtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        savebtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 170, 50));

        namelabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namelabel1.setText("Customer ID");
        jPanel1.add(namelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        custidetxt.setBackground(new java.awt.Color(255, 204, 102));
        custidetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        custidetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        custidetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custidetxtActionPerformed(evt);
            }
        });
        jPanel1.add(custidetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 350, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caridetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caridetxtActionPerformed

    private void rentidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentidtextActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
        new HomeView().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn1ActionPerformed
        try {
            addreturn();
           
        } catch (Exception ex) {
            Logger.getLogger(CarReturnView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_savebtn1ActionPerformed

    private void custidetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custidetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custidetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarReturnView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JTextField caridetxt;
    private javax.swing.JTextField custidetxt;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel idlabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namelabel1;
    private javax.swing.JTextField rentidtext;
    private javax.swing.JButton savebtn1;
    // End of variables declaration//GEN-END:variables

    private void addreturn() throws Exception {
       
   
   
      
        
         CarReturnDto carReturnDto=new CarReturnDto(rentidtext.getText(),custidetxt.getText(),caridetxt.getText(),new Date());
   
    String result=carReturnController.addCarReturn(carReturnDto);
    JOptionPane.showMessageDialog(this, result);
     deleterentdetails();
    clear();
    
    }

    

   

    

    
    private void clear() {
        rentidtext.setText("");
        caridetxt.setText("");
        custidetxt.setText("");
        
    }

    private void deleterentdetails() {
         try {
            String rentId=rentidtext.getText();
            String resp= rentDetailsController.deleteRentDetails(rentId);
            
            JOptionPane.showMessageDialog(this, resp);
            
          
            
        
      } catch (Exception ex) {
            Logger.getLogger(RentView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } 
    }
    

    
    

    
    }
    

