/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentcar.layerd.view;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import rentcar.layerd.controller.RentController;
import rentcar.layerd.controller.RentDetailsController;
import rentcar.layerd.dto.CustomerDto;
import rentcar.layerd.dto.RentDetailsDto;
import rentcar.layerd.dto.RentDto;
import rentcar.layerd.view.HomeView;
import rentcar.layerd.view.CustomerDetailsView;
import rentcar.layerd.view.UpdateRentView;

/**
 *
 * @author TOSHIBA
 */
public class RentView extends javax.swing.JFrame {
    public static RentView instance;
    
    public JTextField txtid;
     public JTextField txtnic;
     public JTextField txtcarid;

    private RentController rentController;
    private RentDetailsController rentDetailsController;
    SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");
    public RentView() {
        
       rentController=new RentController();
       rentDetailsController=new RentDetailsController();
        initComponents();
        instance=this;
        txtid=custid;
        txtnic=custnictext;
       txtcarid= caridtext;
        loadAllrents();
        Color color1=rentIdtext.getBackground();
        fromdate.setBorder(new LineBorder(color1));
        todate.setBorder(new LineBorder(color1));
        
         for( Component c : fromdate.getComponents()){
((JComponent)c).setBackground(color1); 
}
         
   for( Component c : todate.getComponents()){
((JComponent)c).setBackground(color1); 

}       
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        customerTitleLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        rentIdtext = new javax.swing.JTextField();
        custIdLabel = new javax.swing.JLabel();
        caridtext = new javax.swing.JTextField();
        custniclabel = new javax.swing.JLabel();
        customerAddressLabel = new javax.swing.JLabel();
        advancetxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        customerrentidlabel = new javax.swing.JLabel();
        balancetxt = new javax.swing.JTextField();
        customerContacttxt = new javax.swing.JLabel();
        btnsearchcar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fromdate = new com.toedter.calendar.JDateChooser();
        todate = new com.toedter.calendar.JDateChooser();
        custnictext = new javax.swing.JTextField();
        perdaypricetxt = new javax.swing.JTextField();
        customerAddressLabel2 = new javax.swing.JLabel();
        customerContacttxt1 = new javax.swing.JLabel();
        customerAddressLabel3 = new javax.swing.JLabel();
        refundtxt = new javax.swing.JTextField();
        addCustButton = new javax.swing.JButton();
        btnsearchcust = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        custid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 153, 102));

        headerlabel.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("CarHire");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1404, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        homepanel.setPreferredSize(new java.awt.Dimension(800, 400));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerTitleLabel.setText("From");
        homepanel.add(customerTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 50, 40));

        customerIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerIdLabel.setText("Customer");
        homepanel.add(customerIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        rentIdtext.setBackground(new java.awt.Color(255, 204, 102));
        rentIdtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rentIdtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        rentIdtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentIdtextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rentIdtextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rentIdtextMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rentIdtextMouseReleased(evt);
            }
        });
        rentIdtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rentIdtextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rentIdtextKeyReleased(evt);
            }
        });
        homepanel.add(rentIdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 290, 40));

        custIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custIdLabel.setText("Car");
        homepanel.add(custIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 34));

        caridtext.setBackground(new java.awt.Color(255, 204, 102));
        caridtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caridtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        caridtext.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        caridtext.setEnabled(false);
        caridtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caridtextMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                caridtextMouseReleased(evt);
            }
        });
        caridtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridtextActionPerformed(evt);
            }
        });
        caridtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caridtextKeyReleased(evt);
            }
        });
        homepanel.add(caridtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 290, 40));

        custniclabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custniclabel.setText("To");
        homepanel.add(custniclabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 40, 40));

        customerAddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerAddressLabel.setText("Advanced Payment (Rs)");
        homepanel.add(customerAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 210, 34));

        advancetxt.setBackground(new java.awt.Color(255, 204, 102));
        advancetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        advancetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        advancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancetxtActionPerformed(evt);
            }
        });
        advancetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                advancetxtKeyReleased(evt);
            }
        });
        homepanel.add(advancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 290, 40));

        totaltxt.setBackground(new java.awt.Color(255, 204, 102));
        totaltxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totaltxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });
        totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totaltxtKeyReleased(evt);
            }
        });
        homepanel.add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 290, 40));

        customerrentidlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerrentidlabel.setText(" ID");
        homepanel.add(customerrentidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 31));

        balancetxt.setBackground(new java.awt.Color(255, 204, 102));
        balancetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balancetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });
        balancetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                balancetxtKeyReleased(evt);
            }
        });
        homepanel.add(balancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 290, 40));

        customerContacttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerContacttxt.setText("Balance (Rs)");
        homepanel.add(customerContacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 112, 27));

        btnsearchcar.setBackground(new java.awt.Color(255, 153, 0));
        btnsearchcar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsearchcar.setText("Search");
        btnsearchcar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnsearchcar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearchcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcarActionPerformed(evt);
            }
        });
        homepanel.add(btnsearchcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 120, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("New Rent");
        homepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 332, 40));

        fromdate.setBackground(new java.awt.Color(255, 204, 102));
        fromdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        fromdate.setDateFormatString("yyyy-MM-dd ");
        fromdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromdate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fromdateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        homepanel.add(fromdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 210, 40));

        todate.setBackground(new java.awt.Color(255, 204, 102));
        todate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        todate.setDateFormatString("yyyy-MM-dd ");
        todate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                todateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        homepanel.add(todate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 220, 40));

        custnictext.setBackground(new java.awt.Color(255, 204, 102));
        custnictext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custnictext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        custnictext.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        custnictext.setEnabled(false);
        custnictext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custnictextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                custnictextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                custnictextMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                custnictextMouseReleased(evt);
            }
        });
        custnictext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custnictextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                custnictextKeyReleased(evt);
            }
        });
        homepanel.add(custnictext, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 370, 40));

        perdaypricetxt.setBackground(new java.awt.Color(255, 204, 102));
        perdaypricetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        perdaypricetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        perdaypricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdaypricetxtActionPerformed(evt);
            }
        });
        perdaypricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                perdaypricetxtKeyReleased(evt);
            }
        });
        homepanel.add(perdaypricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 290, 40));

        customerAddressLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerAddressLabel2.setText("Per Day Rent (Rs)");
        homepanel.add(customerAddressLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 34));

        customerContacttxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerContacttxt1.setText("Total (Rs)");
        homepanel.add(customerContacttxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 112, 27));

        customerAddressLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerAddressLabel3.setText("Refundable Deposit (Rs) ");
        homepanel.add(customerAddressLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 34));

        refundtxt.setBackground(new java.awt.Color(255, 204, 102));
        refundtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refundtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        refundtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundtxtActionPerformed(evt);
            }
        });
        refundtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                refundtxtKeyReleased(evt);
            }
        });
        homepanel.add(refundtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 290, 40));

        addCustButton.setBackground(new java.awt.Color(255, 153, 0));
        addCustButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addCustButton.setIcon(new javax.swing.ImageIcon("D:\\Projects\\LayerdArchitecture\\rentcar-layerd\\src\\images\\iconsave.png")); // NOI18N
        addCustButton.setText("Save ");
        addCustButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustButtonActionPerformed(evt);
            }
        });
        homepanel.add(addCustButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 150, 50));

        btnsearchcust.setBackground(new java.awt.Color(255, 153, 0));
        btnsearchcust.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsearchcust.setText("Search");
        btnsearchcust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnsearchcust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearchcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcustActionPerformed(evt);
            }
        });
        homepanel.add(btnsearchcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 120, 39));

        btnback.setBackground(new java.awt.Color(255, 153, 0));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("D:\\Projects\\LayerdArchitecture\\rentcar-layerd\\src\\images\\iconback.png")); // NOI18N
        btnback.setText("Back");
        btnback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        homepanel.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 170, 50));

        custid.setBackground(new java.awt.Color(255, 204, 102));
        custid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        custid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        custid.setEnabled(false);
        custid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                custidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                custidMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                custidMouseReleased(evt);
            }
        });
        custid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                custidKeyReleased(evt);
            }
        });
        homepanel.add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 290, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Projects\\LayerdArchitecture\\rentcar-layerd\\src\\images\\log9.jpg")); // NOI18N
        homepanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentIdtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentIdtextMouseClicked

    }//GEN-LAST:event_rentIdtextMouseClicked

    private void rentIdtextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentIdtextMouseEntered

    }//GEN-LAST:event_rentIdtextMouseEntered

    private void rentIdtextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentIdtextMouseExited

    }//GEN-LAST:event_rentIdtextMouseExited

    private void rentIdtextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentIdtextMouseReleased

    }//GEN-LAST:event_rentIdtextMouseReleased

    private void rentIdtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentIdtextKeyPressed

    }//GEN-LAST:event_rentIdtextKeyPressed

    private void rentIdtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentIdtextKeyReleased

    }//GEN-LAST:event_rentIdtextKeyReleased

    private void advancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advancetxtActionPerformed

    private void advancetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advancetxtKeyReleased

    }//GEN-LAST:event_advancetxtKeyReleased

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void totaltxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totaltxtKeyReleased

    }//GEN-LAST:event_totaltxtKeyReleased

    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtActionPerformed

    private void balancetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balancetxtKeyReleased

    }//GEN-LAST:event_balancetxtKeyReleased

    private void btnsearchcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcarActionPerformed
new AvailableCarView().setVisible(true);
    }//GEN-LAST:event_btnsearchcarActionPerformed

    private void fromdateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fromdateAncestorAdded
       
    }//GEN-LAST:event_fromdateAncestorAdded

    private void todateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_todateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_todateAncestorAdded

    private void custnictextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custnictextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextMouseClicked

    private void custnictextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custnictextMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextMouseEntered

    private void custnictextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custnictextMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextMouseExited

    private void custnictextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custnictextMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextMouseReleased

    private void custnictextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custnictextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextKeyPressed

    private void custnictextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custnictextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_custnictextKeyReleased

    private void perdaypricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdaypricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perdaypricetxtActionPerformed

    private void perdaypricetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perdaypricetxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_perdaypricetxtKeyReleased

    private void refundtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refundtxtActionPerformed

    private void refundtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refundtxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_refundtxtKeyReleased

    private void caridtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caridtextKeyReleased

    }//GEN-LAST:event_caridtextKeyReleased

    private void caridtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caridtextActionPerformed

    private void caridtextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caridtextMouseReleased

    }//GEN-LAST:event_caridtextMouseReleased

    private void caridtextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caridtextMouseExited

    }//GEN-LAST:event_caridtextMouseExited

    private void addCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustButtonActionPerformed
        try {
            addrent();
        } catch (Exception ex) {
            Logger.getLogger(RentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCustButtonActionPerformed

    private void btnsearchcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcustActionPerformed

new CustomerDetailsView().setVisible(true);
setnic();
    }//GEN-LAST:event_btnsearchcustActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
       dispose();
       new HomeView().setVisible(true);
       
    }//GEN-LAST:event_btnbackActionPerformed

    private void custidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_custidMouseClicked

    private void custidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custidMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_custidMouseEntered

    private void custidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custidMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_custidMouseExited

    private void custidMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custidMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_custidMouseReleased

    private void custidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_custidKeyPressed

    private void custidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_custidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustButton;
    private javax.swing.JTextField advancetxt;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsearchcar;
    private javax.swing.JButton btnsearchcust;
    private javax.swing.JTextField caridtext;
    private javax.swing.JLabel custIdLabel;
    private javax.swing.JTextField custid;
    private javax.swing.JLabel custniclabel;
    private javax.swing.JTextField custnictext;
    private javax.swing.JLabel customerAddressLabel;
    private javax.swing.JLabel customerAddressLabel2;
    private javax.swing.JLabel customerAddressLabel3;
    private javax.swing.JLabel customerContacttxt;
    private javax.swing.JLabel customerContacttxt1;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JLabel customerTitleLabel;
    private javax.swing.JLabel customerrentidlabel;
    private com.toedter.calendar.JDateChooser fromdate;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField perdaypricetxt;
    private javax.swing.JTextField refundtxt;
    private javax.swing.JTextField rentIdtext;
    private com.toedter.calendar.JDateChooser todate;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void addrent() throws Exception {
       RentDto rentDto=new RentDto(rentIdtext.getText(),custid.getText(),fromdate.getDate(),todate.getDate(),caridtext.getText(),
        Double.parseDouble(perdaypricetxt.getText()),Double.parseDouble(advancetxt.getText()),Double.parseDouble(refundtxt.getText()),
       Double.parseDouble(totaltxt.getText()),Double.parseDouble(balancetxt.getText()));
   
    String result=rentController.addRent(rentDto);
    JOptionPane.showMessageDialog(this, result);
    adddetails();
    clear();
    loadAllrents(); 
    }

    private void updaterent() {
      
    }

    private void deleterent() {
      
    }

    private void loadAllrents() {
       
        
    }

    private void clear() {
        rentIdtext.setText("");
        custid.setText("");
        fromdate.setDate(null);
        todate.setDate(null);
       caridtext.setText("");
        perdaypricetxt.setText("");
        advancetxt.setText("");
        refundtxt.setText("");
       totaltxt.setText("");
      balancetxt.setText("");
      custnictext.setText("");
    }

    private void adddetails() throws Exception {
        RentDetailsDto rentDetailsDto=new RentDetailsDto(rentIdtext.getText(),custid.getText(),caridtext.getText(),fromdate.getDate(),todate.getDate(),
        custnictext.getText());
   
    String result=rentDetailsController.addRentDetails(rentDetailsDto);
    JOptionPane.showMessageDialog(this, result); 
    }

    private void setnic() {
        
    }




   
    }

    
    

